# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a4794f89d0e2708dbd3a1eea3f26067f8c187811a2fb107efef01d925cf98fba7a50c79e2789f436341b83d27f505ea0a0cacee4d849622f0e1ca846f2d55c3

test:
  secret_key_base: d47df8f71ac52caf062ab9da9616515c011fb5332e003527a41d475121b39d8cf9d9e081a649502b082ad8b4762af79848af10f4be58cfe2a4da426ac9d1c1a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
